name: Build

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    if: "contains(github.event.head_commit.message, 'publish')"

    steps:
      - uses: actions/checkout@v2

      - name: Set gradle.properties values
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: ./gradle.properties
          contents: |
            aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}
            aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            write-mode: append

      - name: Set build number
        id: buildnumber
        uses: einaregilsson/build-number@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build + Publish to Curse and maven
        run: ./gradlew build curseforge publish
        env:
          BUILD_NUMBER: ${{ steps.buildnumber.outputs.build_number }}

      - name: Set Maven artifact ACL
        uses: jusbrasil/github-action-s3cmd@master
        secrets:
          - ${{ secrets.AWS_ACCESS_KEY_ID }}
          - ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        args:
          - s3cmd setacl s3://tehnut-mod-maven/ --acl-public --recursive
